### ISSUE TITLE
Overworld/ Some End Ores not Mineable with Tinker's Construct Tools

### ISSUE THREAD

**Issue by Lusaphor** [ICannt/Netherending-Ores#10]
Not sure if its a config setting, but the The Overworld and End Quartz, Cobalt, and Ardite are not mineable with any of the tinker's construct tool. No breaking particles or anything, Regular pickaxes work, and all the nether/ most end ores are mineable with the TC tool. I've used every level of pickaxe head but none of the tools interact with the blocks.

**Comment by trabpukcip** [comment]
Confirmed that this is happening in my test pack (which is up to date). I am not doing anything unusual in about the way the harvestability or hardness is being registered. perhaps Tinkers' Construct interfering with itself?

**Comment by Lusaphor** [comment]
No idea, but it like the tools are even register the block since other items (regardless of tool or not) at least do something to the block.

**Comment by trabpukcip** [comment]
What I should have realised a long time ago is that the main block class for these blocks used out of date code that should have been updated when I fixed #3.

So finally fixed :)
