### ISSUE TITLE
Suggestion: Nether Zinc ore and Nether Mercury ore.

### ISSUE THREAD

**Issue by Trinsdar** [ICannt/Netherending-Ores#11]
I noticed when looking through this mod that's their is no nether zinc or Nether Mercury. a couple common mods that add zinc are base metals and tech reborn, and base metals adds mercury..

**Comment by trabpukcip** [comment]
Does any mod besides Base Metals actually implement mercury? Base Metals itself is just a materials mod like Netherending Ores itself. I will look at adding zinc though since it has an actual use.

**Comment by Trinsdar** [comment]
Extra Planets also implements mercury ore but it's a planet specific ore in that mod. So technically base Metals is the only mod that adds overworld mercury.

**Comment by brisingraerowing** [comment]
I second Zinc ore (for use with Railcraft).
