### ISSUE TITLE
Adding Induction Smelter recipes

### ISSUE THREAD

**Issue by Pacca64** [ICannt/Netherending-Ores#13]
In the old CoFH Nether Ores mod, you could use the Induction Smelter to increase the total output of Nether Ores. More specifically, you could use Rich Slag to produce 3 overworld ores instead of two alongside 1 Slag, or smelt it with sand to get two ores have a 10% chance of obtaining Rich Slag.

These missing recipes are the only thing holding me back from fully appreciating this mod.

**Comment by trabpukcip** [comment]
I always intended to add recipes for more advanced machines such as the Induction Smelter. Thermal Expansion can be a bit of a pain due to augments and the ore dictionary setup for TE. I will look into adding the recipes though.
