### ISSUE TITLE
Immersive Engineering crusher support

### ISSUE THREAD

**Issue by Konclan** [ICannt/Netherending-Ores#14]
Add support for crushing the netherending ores directly through an Immersive Engineering crusher. Should take 2x the normal power of the normal ore but give 2x the output in dust. Its just a little frustrating to cook the ore first and then crush it to cook it again.

**Comment by trabpukcip** [comment]
Have not used the API for Immersive Engineering before but sure I can have a look at it sometime.

**Comment by trabpukcip** [comment]
Have started on this, targeting the 1.4 release.

**Comment by trabpukcip** [comment]
This is complete (for now) Arc Furnace and Crusher support.
