### ISSUE TITLE
Project Red

### ISSUE THREAD

**Issue by MaragretRLautzenhiser** [ICannt/Netherending-Ores#16]
Could nether/end versions of the 4 unique project red ores, ruby, sapphire, peridot, and electrotine, be added to the mod?

**Comment by MaragretRLautzenhiser** [comment]
I've actually created the necessary textures, already, based on those from Project Red and Mojang's original textures. If you'd like I could send them to you to use.

**Comment by trabpukcip** [comment]
I will have a look at doing this.
However I tend to like to do the textures myself as I modify the outer edges to improve contrast against the base material.
For example if you have taken the ruby texture from projectred and plonked it onto the netherrack base, it will be hard to see.
Nether Redstone Ore for example has black outlines to separate it from the netherrack.

**Comment by MaragretRLautzenhiser** [comment]
I copied the brightness difference information from the base ores compared to stone and overlaid that also onto netherrack and end stone to subtly outline the ores, as well as increased color saturation on nether ores for greater contrast

**Comment by trabpukcip** [comment]
I never touch the actual ore graphics and rely on what can be done on outlines alone. If you want to remove the saturation tweak and upload them on a gist in a zip I will run them through pngcrush and include them. The updated blockstate files has the required png filenames if they are not already correct. https://github.com/ICannt/Netherending-Ores/tree/master/src/main/resources/assets/netherendingores/blockstates
