### ISSUE TITLE
Ores not spawning

### ISSUE THREAD

**Issue by mitchngwen** [ICannt/Netherending-Ores#18]
No ores spawning in the nether. I am just wondering if I am missing something.

**Comment by trabpukcip** [comment]
You need CoFH World installed along with ore spawning configuration files for anything to spawn.
Please see the related project: [https://www.curseforge.com/minecraft/customization/netherending-ores-configs](url)
I have just updated those configs too to clear some things up and make it easier to understand.

**Comment by mitchngwen** [comment]
That fixed it right away, thank you very much.
