### ISSUE TITLE
Netherending ores processing

### ISSUE THREAD

**Issue by xJon** [ICannt/Netherending-Ores#19]
Is there a way to avoid this issue?
![Screenshot_5](https://user-images.githubusercontent.com/8945347/63214228-de28a800-c158-11e9-9ad1-5993558899f7.png)
![Screenshot_4](https://user-images.githubusercontent.com/8945347/63214229-df59d500-c158-11e9-853f-c194cd74258f.png)
I'd like the redstone furnace and vanilla furnace to output the same amount of ore.
Thanks!

**Comment by trabpukcip** [comment]
By default it only has full ore output when augmented i.e. with flux anodizers. It was designed this way so the output was no excessive when using augments. There is no way to disable augments for a particular recipe, this is by Thermal Foundation's design. There is config options to change this behaviour. See machine recipe settings in the config file. Up to you if you want to disable augments through removing their recipes.

**Comment by xJon** [comment]
Uh, I see, so it was built this way to make augments too overpowered?
If so, that seems fine. Thank you!
