### ISSUE TITLE
Support for More Ores

### ISSUE THREAD

**Issue by Mikaliv** [ICannt/Netherending-Ores#20]
I love this mod!  Thank you so much for putting it together.  Is there any chance we could get ores from the Nuclearcraft Mod included.  

This includes Magnesium, Thorium, Lithium and Boron.

**Comment by trabpukcip** [comment]
I will look into it, however not at the moment as I am in the middle of adding a bunch of other features. So it won't be until after the 1.4 release.

**Comment by Mikaliv** [comment]
Ok...thanks for the reply...I'll be looking for it in 1.14. :)

**Comment by trabpukcip** [comment]
Suggestions from Curseforge: Betweenlands, BoP and maybe Quark (might not make sense).
