### ISSUE TITLE
Ores don't spawn in End

### ISSUE THREAD

**Issue by SylvanusPC** [ICannt/Netherending-Ores#23]
Hello,
My friend and I are putting together a small-ish modpack for ourselves and our friends, and we're running into an issue with ores generating in the End. I've used this mod before and have always been pleased with it, but for some reason this time I can't get ores to spawn in the End despite including the files in the config\cofh\world\. Attached is a screenshot for proof:
![enderores](https://user-images.githubusercontent.com/30609492/78386230-3064ef00-75ab-11ea-976e-24b797c044e6.png)
There are no error logs or anything indicating that there's a problem, and I would assume I've done it wrong except that I've done this before and it's always worked previously. Of course, I'm not going to count that out as a possibility. Any help would be appreciated, thanks!

**Comment by trabpukcip** [comment]
Did you dig beneath the surface or fly around the sides at all?
I designed the height levels to not show ores on the surface.
I did this to try and stop people swiss cheesing the surface, so the dragon can respawn without a mess.

Also is cofhworld spitting out errors at all?
If for some reason the files are invalid it will tell you about it.

If you want me to look at the pack for you, you can send me a private message with a pack upload link if you like.

**Comment by SylvanusPC** [comment]
I had dug around and flew under/around to see if they had spawned and they hadn't. I checked the log and nothing was giving me any errors, so as a precaution I removed the mod and files and loaded it back into the pack, creating a new world. Seemed to fix whatever the problem was. Thank you for the help (and quick response)!
