### ISSUE TITLE
[Crash] IC2 Classic mining laser causes ore explosions to crash the game.

### ISSUE THREAD

**Issue by SlayerTheChikken** [ICannt/Netherending-Ores#26]
https://paste.mod.gg/udilelejon.mccrash
[latest.log](https://github.com/ICannt/Netherending-Ores/files/6357277/latest.log)

Be in survival mode with mining laser fully charged, shoot nether ores till one explodes, crash.

**Comment by trabpukcip** [comment]
Hmm, the laser may be removing the block in a weird way. By the time the explosion goes to trigger, the block is already gone.

**Comment by SlayerTheChikken** [comment]
This is indeed the case, the explosion does still occur however, the crash just needs to be caught when blocks happen to poof during/before the resistance check.
