### ISSUE TITLE
No ores in end dimension.

### ISSUE THREAD

**Issue by NoWway** [ICannt/Netherending-Ores#27]
I saw with jei that netherending ores added ores in the end, but I can't seem to find any, I read somewhere that they are intended to not spawn at the surface but after digging there really isn't anything, I also can't seem to find resonant ender ore which is probably a related issue. I'm on version 1.12.2 of minecraft and running the enigmatica modpack.

**Comment by NoWway** [comment]
I also forgot to mention that, I did remove and put back the mod file but to no avail.

**Comment by trabpukcip** [comment]
I assume it is Enigmatica Expert 2 that you are talking about. The reason why the ores are not spawning is that they are not configured to do so. The stock configs are listed on github https://github.com/NillerMedDild/Enigmatica2Expert/tree/master/config/cofh/world and if you look at the file names (and examine the contents) you see that there is no config file for The End. You would have to add your own config files if you want to add my end ores. Resonant Ender could also be added in. Of course adding the files in means the pack is no longer a "standard" config and could result in changes to progression.
