### ISSUE TITLE
Support for 1.14+ (1.16.5, 1.18.2, 1.19.1)

### ISSUE THREAD

**Issue by GamingNerdLeith** [ICannt/Netherending-Ores#28]
Is it possible for you to add support for the newer version of Minecraft and Forge, 1.12.2 is now (Unforetuneatly) obsolete and many mods have migrated to the newer versions of Minecraft, with the exeption of Netherending-Ores. I love the fact that ores can appear in all of the three vanilla dimention, but i would not be able to enjoy it in the newer versions of Minecraft and the alternative are very poorly written.

**Comment by trabpukcip** [comment]
![2022-08-06_21 19 31](https://user-images.githubusercontent.com/4687400/183251097-ed8f26dc-54d4-48e9-8a50-2ec7bf3082bd.png)

**Comment by GamingNerdLeith** [comment]
![image](https://user-images.githubusercontent.com/67237948/183251191-c0e1f5de-2d89-4495-beac-4ea646c58f0a.png)
Thanks, but I cant see it. Where is it on curseforge? https://www.curseforge.com/minecraft/mc-mods/netherending-ores
Is the github version the only one that supports 1.14+?

**Comment by trabpukcip** [comment]
That was a teaser, it is in the middle of development and isn't public yet. It will be for 1.19.1 and possibly 1.18.2 as it is being developed under it.
