### ISSUE TITLE
Mod is unavailable on Third-party Launchers

### ISSUE THREAD

**Issue by DDriggs00** [ICannt/Netherending-Ores#29]
You have the Curseforge "Prevent Third-Party Distribution" setting enabled, which prevents your mod from being used on third-party launchers. Many people do not want to use the Overwolf launcher due to privacy and data-harvesting concerns, or inaccessibility on Linux, and this restriction makes it difficult for those people to use modpacks with your mod in them, as well as discouraging pack developers from including your mod. Additionally, it makes it much more difficult to host a server with this mod. For more details, see https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

I assume that this is unintentional, since you are using a GPL License.

**Comment by trabpukcip** [comment]
Sorry I don't intend to change anything at this point in time.

**Comment by james-pre** [comment]
@DDriggs00,

Since this is licensed under GPL, you can always just publish it yourself. Perhaps on Modrinth? Then, tools like [Ferium](https://github.com/gorilla-devs/ferium) will just pick it up when adding it to a profile. If you'd like, I may be able to help.

**Comment by trabpukcip** [comment]
Sure it can be republished but not under the current mod name. The reason why I am not changing things is that I am not actively supporting/developing the mod, my current pc doesn't have a dev environment setup, let alone for a 1.12.2 mod.

**Comment by james-pre** [comment]
@trabpukcip,

I don't think the change requires you to do any development, probably just a setting in Curseforge.

**Comment by trabpukcip** [comment]
I am well aware of that, I know where said setting is, direct downloads from Curseforge are to remain the only way to obtain the mod.
