### ISSUE TITLE
Different aluminum texture

### ISSUE THREAD

**Issue by SynexWolf** [ICannt/Netherending-Ores#9]
I've noticed that the aluminum ore's texture is different compared to the ore in thermal expansion. I expected the texture to be a white color, but instead it's more orange.
It doesn't have to be changed, but I thought I'll just give a heads up.

**Comment by trabpukcip** [comment]
It is more pink but anyway, apparently the base textures for Thermal Foundation were changed back in January. Aluminium Ore did used to look like that. I will assess all of the changes at some point and update the textures.
